name: sparrow-ipc
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - ninja
  - cxx-compiler
  # Libraries dependencies
  - flatbuffers
  - lz4-c
  - zstd
  - nlohmann_json
  - sparrow-devel >=2.1.0
  - sparrow-json-reader >=2.1.0
  # Testing dependencies
  - doctest
  # Documentation dependencies
  - doxygen
  - graphviz
